server:
  port: 8091
spring:
  application:
    name: springboot-session
  redis:
    host: localhost
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 4
        max-wait: 10000
    database: 3
  ##把当前mybatis的数据源和数据库连接到操作从mybatis直接转移到交给spring管理
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 测试环境
    url: jdbc:mysql://localhost:3306/test?useSSL=false&testOnBorrow=true&testWhileIdle=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    ## 使用数据库的连接池----注意这个是hikari 默认springboot自带的，目前性能最强
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 300000
      connection-test-query: SELECT 1


##由mybatis提供的直接免写mybatis.xml文件的配置方案
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.dto
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    ##开启驼峰识别，可以使得我们的实体对象的属性和数据表字段的列名驼峰转换 表  class_id    实体类  classId
    map-underscore-to-camel-case: true


# 日志配置
logging:
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    #不同目录下的日志可配置不同级别
    com.example.mapper: DEBUG

