server:
  port: 8090
  servlet:
    context-path: /cache2
spring:
  application:
    name: springboot-customcache

##把当前mybatis的数据源和数据库连接到操作从mybatis直接转移到交给spring管理
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 测试环境
    url: jdbc:mysql://localhost:3306/test?useSSL=false&testOnBorrow=true&testWhileIdle=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    ## 使用数据库的连接池----注意这个是hikari 默认springboot自带的，目前性能最强
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 300000
      connection-test-query: SELECT 1
#mybatis-plus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true

# 日志配置
logging:
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    #不同目录下的日志可配置不同级别
    com.example.dao: DEBUG

