server:
  port: 8097
spring:
  application:
    name: springboot-session04
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 3
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 4
        max-wait: 10000